# Generated by Django 5.2.4 on 2025-07-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=255)),
                ('source', models.CharField(default='organic', max_length=64)),
                ('visited_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
