# Generated by Django 5.2.4 on 2025-07-24 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyForCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ready_status', to='orders.order')),
            ],
        ),
    ]
