# Generated by Django 5.2.4 on 2025-07-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_readyforcourier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent_to_courier',
            field=models.BooleanField(default=False),
        ),
    ]
