# Generated by Django 5.2.4 on 2025-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_sent_to_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(default='organic', max_length=20),
        ),
    ]
