# Generated by Django 5.2.4 on 2025-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_created_at_orderitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
