# Generated by Django 5.2.4 on 2025-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
