# Generated by Django 5.2.4 on 2025-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_courier_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('hold', 'Hold'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('failed', 'Failed'), ('partially_returned', 'Partially Returned'), ('paid_returned', 'Paid Returned')], default='pending', max_length=20),
        ),
    ]
