# Generated by Django 5.2.4 on 2025-10-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
