# Generated by Django 5.2.4 on 2025-10-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_courier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inside_dhaka',
            field=models.BooleanField(default=False),
        ),
    ]
