# Generated by Django 5.2.4 on 2025-10-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_confirmed_by_order_confirmed_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_by_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
