# Generated by Django 5.2.4 on 2025-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_confirmed_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
    ]
