# Generated by Django 5.2.4 on 2025-12-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='z_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(max_length=40),
        ),
    ]
