# Generated by Django 5.2.4 on 2025-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='compared_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, help_text='Flat discount amount, not a percentage', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='net_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
