# Generated by Django 5.2.4 on 2025-07-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_deleted_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
