# Generated by Django 5.2.4 on 2025-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('images', '0001_initial'),
        ('products', '0005_product_total_orders'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_active_sku',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sku', 'slug'), name='unique_active_sku_&_slug'),
        ),
    ]
