import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import { SessionProvider } from "next-auth/react";
import { CartProvider } from "@/stores/cart";
import { Toaster } from "react-hot-toast";
import { OrderProvider } from "@/stores/orders";
import ScrollToTop from "@/components/ScrollToTop";
import Image from "next/image";
import { PathaoProvider } from "@/stores/pathao";
import { ProductsProvider } from "@/stores/products";
import Footer from '@/components/Footer'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-auto`}
      >
        <SessionProvider>
          <CartProvider>
            <OrderProvider>
              <PathaoProvider>
                <ProductsProvider>
                  <Toaster />
                  <ScrollToTop />
                  <Navbar />
                  <div className="min-h-[calc(100vh-(60px+20px+40px+250px+10px))]">
                    {children}
                  </div>
                  <Footer/>
                </ProductsProvider>
              </PathaoProvider>
            </OrderProvider>
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
