# Generated by Django 5.2.4 on 2025-07-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_price',
            new_name='ordered_price',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='is_refunded',
            new_name='refunded',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='refunded_at',
        ),
    ]
