# Generated by Django 5.2.4 on 2025-07-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('notice', '0001_initial'),
        ('products', '0002_rename_discounted_price_product_compared_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notice', 'Notice'), ('navbar', 'Navbar'), ('image_slider', 'Image Slider'), ('categories_bar', 'Categories Bar'), ('products', 'Products'), ('products_slider', 'Products Slider'), ('category', 'Category')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('image_each_slide', models.PositiveIntegerField(blank=True, null=True)),
                ('products_each_slide', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='categories.category')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_feed', to='categories.category')),
                ('notices', models.ManyToManyField(blank=True, to='notice.notice')),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
