# Generated by Django 5.2.4 on 2025-07-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedsection',
            name='images',
        ),
        migrations.AddField(
            model_name='feedsection',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.uploadedimage'),
        ),
    ]
