# Generated by Django 5.2.4 on 2025-07-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_feedsection_images_feedsection_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsection',
            name='slides',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
