# Generated by Django 5.2.4 on 2025-07-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feedsection_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsection',
            name='args',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
