# Generated by Django 5.2.4 on 2025-07-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_feedsection_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsection',
            name='type',
            field=models.CharField(choices=[('notice', 'Notice'), ('navbar', 'Navbar'), ('image_slider', 'Image Slider'), ('categories_bar', 'Categories Bar'), ('categories_slider', 'Categories Slider'), ('products', 'Products'), ('products_slider', 'Products Slider'), ('category', 'Category'), ('footer', 'Footer')], max_length=32),
        ),
    ]
